class UserError(Exception):
    pass

class AlreadyExists(Exception):
    pass